name: Release

on:
  push:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin, js]
        goarch: [amd64, wasm]
        exclude:
          - goarch: wasm
            goos: darwin
          - goarch: wasm
            goos: windows
          - goarch: wasm
            goos: linux

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Go Release Binaries (server)
        uses: wangyoucao577/go-release-action@v1.18
        if: matrix.goarch != 'wasm' && matrix.goos != 'js'
        with:
          goversion: 1.16
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          release_tag: dev
          overwrite: true
          md5sum: false
          binary_name: mm2-tools-server
          project_path: cmd_server
          ldflags: -X main.gitCommit=${{ github.sha }} -X main.gitRef=${{ github.ref }}
          asset_name: "mm2-tools-server-dev-${{ matrix.goos }}-${{ matrix.goarch }}"

      - name: Go Release Binaries (mm2-wasm)
        uses: wangyoucao577/go-release-action@v1.18
        if: matrix.goarch == 'wasm' && matrix.goos == 'js'
        with:
          goversion: 1.16
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          release_tag: dev
          overwrite: true
          md5sum: false
          binary_name: mm2-tools.wasm
          project_path: wasm_mm2_tools
          asset_name: "mm2-tools-dev-${{ matrix.goos }}-${{ matrix.goarch }}"

      - name: Go Release Binaries (client)
        uses: wangyoucao577/go-release-action@v1.18
        if: matrix.goarch != 'wasm' && matrix.goos != 'js'
        with:
          goversion: 1.16
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          release_tag: dev
          overwrite: true
          md5sum: false
          binary_name: mm2-tools-client
          project_path: cmd_client
          ldflags: -X main.gitCommit=${{ github.sha }} -X main.gitRef=${{ github.ref }}
          asset_name: "mm2-tools-client-dev-${{ matrix.goos }}-${{ matrix.goarch }}"