name: Release

on:
  push:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin, freebsd]
        goarch: [amd64]

    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Go Release Binaries
        uses: wangyoucao577/go-release-action@v1.17
        with:
          goversion: 1.16
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          release_tag: dev
          overwrite: true
          build_flags: cmd/mm2_tools_server.go
          binary_name: mm2-tools-server
          ldflags: -X main.gitCommit=${{ github.sha }} -X main.gitRef=${{ github.ref }}